apiVersion: apps/v1
kind: Deployment
metadata:
  name: bio-db-deployment
  labels:
    name: bio-db-deployment
    app: bio-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: sankethsk/bio-db:1.0
          env:
            - name: POSTGRES_DB
              value: "biogas"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
          ports:
            - containerPort: 5432